// types/users.ts

export enum Role {
  ADMIN = "ADMIN",
  TEACHER = "TEACHER",
  THERAPIST = "THERAPIST",
  PROVIDER = "PROVIDER",
  SUPERVISOR = "SUPERVISOR",
}

export enum SecurityLevel {
  FULL_ACCESS = "FULL_ACCESS",
  LIMITED = "LIMITED",
  READ_ONLY = "READ_ONLY",
}

export enum Status {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
}

export enum Permission {
  MANAGE_USERS = "MANAGE_USERS",
  ASSIGN_ROLES = "ASSIGN_ROLES",
  DEACTIVATE_USERS = "DEACTIVATE_USERS",
  RESET_PASSWORDS = "RESET_PASSWORDS",
  CONFIGURE_TEST_SITES = "CONFIGURE_TEST_SITES",
  SCHEDULE_TESTS = "SCHEDULE_TESTS",
  ASSIGN_ACCOMMODATIONS = "ASSIGN_ACCOMMODATIONS",
  TRACK_STUDENT_CONFIRMATIONS = "TRACK_STUDENT_CONFIRMATIONS",
  MANAGE_EQUIPMENT = "MANAGE_EQUIPMENT",
  MANAGE_TESTS = "MANAGE_TESTS",
  ASSIGN_STUDENTS = "ASSIGN_STUDENTS",
  TRACK_ATTENDANCE = "TRACK_ATTENDANCE",
  SEND_REMINDERS = "SEND_REMINDERS",
  VIEW_REPORTS = "VIEW_REPORTS",
  SCAN_QR_CODES = "SCAN_QR_CODES",
  REPORT_INCIDENTS = "REPORT_INCIDENTS",
  CONFIRM_TEST_LOCATION = "CONFIRM_TEST_LOCATION",
  VIEW_RESULTS = "VIEW_RESULT",
}
